### ISSUE TITLE
Default colors too dim for unmatched characters

### ISSUE THREAD

**Issue by basarat** [atom-community/autocomplete-plus#255]
Default: 
![image](https://cloud.githubusercontent.com/assets/874898/6121698/fbe253aa-b13b-11e4-8014-f297bb71a439.png)

Recommend:

![image](https://cloud.githubusercontent.com/assets/874898/6121685/d6e6df6c-b13b-11e4-8ebc-fe3c84a45761.png)

CSS 
```css
    autocomplete-suggestion-list.select-list.popover-list ol.list-group li {
        color: rgba(230, 230, 230, 0.9);
    }
```
